/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentaldvd;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.*;

/**
 *
 * @author hiccu
 */
public class formFilem extends javax.swing.JFrame {
    
    String judulKolom[]={"Kode Film","Judul","Genre","Tahun","Asal","Stok"};
    String sqlFilm="SELECT*FROM film";
    int lebarKolom[]={100,300,100,60,200,60};

    /**
     * Creates new form formFilem
     */
    public formFilem() {
        initComponents();
        
        this.setLocationRelativeTo(null); // untuk memposisikan form ditengah layar
        new ConfigDB().tampilTabel(judulKolom, sqlFilm, JTableFilm);
        new ConfigDB().aturLebarKolom(JTableFilm, lebarKolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JLabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        JLabel4 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        JLabel6 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        txtAsal = new javax.swing.JTextField();
        cmbGenre = new javax.swing.JComboBox<>();
        txtStok = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableFilm = new javax.swing.JTable();
        JLabel7 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabel1.setText("Kode Film");
        JLabel1.setName("JLabel1"); // NOI18N

        JLabel2.setText("Judul");
        JLabel2.setName("JLabel2"); // NOI18N

        JLabel3.setText("Genre");
        JLabel3.setName("JLabel3"); // NOI18N

        JLabel4.setText("Tahun");
        JLabel4.setName("JLabel4"); // NOI18N
        JLabel4.setOpaque(true);

        JLabel5.setText("Asal Negara");
        JLabel5.setName("JLabel5"); // NOI18N

        JLabel6.setText("Stok");
        JLabel6.setName("JLabel6"); // NOI18N

        txtKode.setName("txtKode"); // NOI18N

        txtJudul.setName("txtJudul"); // NOI18N

        txtTahun.setName("txtTahun"); // NOI18N

        txtAsal.setName("txtAsal"); // NOI18N

        cmbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Judul", "Action", "Adventre", "Animation", "Biography", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "Histroy", "Horror", "Musical", "Mystery", "Sport", "Thriller", "War", "Western" }));
        cmbGenre.setName("cmbGenre"); // NOI18N

        txtStok.setName("txtStok"); // NOI18N

        btnSimpan.setText("Simpan");
        btnSimpan.setName("btnSimpan"); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setName("tbnHapus"); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.setName("btnUbah"); // NOI18N
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.setName("btnClear"); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        JTableFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableFilm.setName("JTableFilm"); // NOI18N
        JTableFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableFilmMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTableFilm);

        JLabel7.setText("Pencarian Judul Film");
        JLabel7.setName("JLabel7"); // NOI18N

        txtCari.setName("txtCari"); // NOI18N
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.setName("btnRefresh"); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabel1)
                                    .addComponent(JLabel2)
                                    .addComponent(JLabel3)
                                    .addComponent(JLabel5)
                                    .addComponent(JLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTahun)
                                    .addComponent(txtKode)
                                    .addComponent(txtJudul)
                                    .addComponent(txtAsal)
                                    .addComponent(cmbGenre, 0, 218, Short.MAX_VALUE)
                                    .addComponent(txtStok)))
                            .addComponent(JLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel2)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel3)
                    .addComponent(cmbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel4)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel5)
                    .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel6)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );

        JLabel1.getAccessibleContext().setAccessibleName("");
        JLabel2.getAccessibleContext().setAccessibleName("");
        JLabel3.getAccessibleContext().setAccessibleName("");
        JLabel4.getAccessibleContext().setAccessibleName("");
        JLabel5.getAccessibleContext().setAccessibleName("");
        JLabel6.getAccessibleContext().setAccessibleName("");
        txtKode.getAccessibleContext().setAccessibleName("");
        txtJudul.getAccessibleContext().setAccessibleName("");
        txtTahun.getAccessibleContext().setAccessibleName("");
        txtAsal.getAccessibleContext().setAccessibleName("");
        cmbGenre.getAccessibleContext().setAccessibleName("");
        txtStok.getAccessibleContext().setAccessibleName("");
        btnSimpan.getAccessibleContext().setAccessibleName("");
        btnHapus.getAccessibleContext().setAccessibleName("");
        btnUbah.getAccessibleContext().setAccessibleName("");
        btnClear.getAccessibleContext().setAccessibleName("");
        JLabel7.getAccessibleContext().setAccessibleName("");
        btnRefresh.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    try {
            if (txtKode.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Kode film belum diisi");
                txtKode.requestFocus();
            } else if (txtJudul.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Judul film belum diisi");
                txtJudul.requestFocus();
            } else if (String.valueOf(cmbGenre.getSelectedItem())== "..Pilih Judul..") {
                JOptionPane.showMessageDialog(null, "Genre film belum diisi");
                cmbGenre.requestFocus();
            } else if (txtTahun.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tahun belum diisi");
                txtTahun.requestFocus();
            } else if (txtAsal.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Asal Negara film belum diisi");
                txtAsal.requestFocus();
            } else if (txtStok.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Stok film belum diisi");
                txtStok.requestFocus();
            } else if(new ConfigDB().duplikasiData("film", "KodeFilm", txtKode.getText())==true) {
                JOptionPane.showMessageDialog(null, "Kode Film sudah terdaftar");
                Statement st = new ConfigDB().koneksi.createStatement();
                ResultSet rs = st.executeQuery("SELECT* FORM film WHERE KodeFilm = "+txtKode.getText()+"'");
                if (rs.next()) {
                    txtJudul.setText(rs.getString("Judul"));
                    cmbGenre.setSelectedItem(String.valueOf(rs.getString("Genre")));
                    txtTahun.setText(rs.getString("tahun"));
                    txtAsal.setText(rs.getString("asal"));
                    txtStok.setText(rs.getString("stok"));
                }
            } else {
                String SQL = "INSERT INTO film VALUES ("
                        + "'"+txtKode.getText()+"'"
                        + ",'"+txtJudul.getText()+"'"
                        + ",'"+String.valueOf(cmbGenre.getSelectedItem())+"'"
                        + ",'"+txtTahun.getText()+"'"
                        + ",'"+txtAsal.getText()+"'"
                        + ",'"+txtStok.getText()+"')";
                new ConfigDB().simpanData(SQL);
                new ConfigDB().tampilTabel(judulKolom, sqlFilm, jTable1);
                new ConfigDB().aturLebarKolom(jTable1, lebarKolom);
            }
        } catch (Exception e) {
            
        }   
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
 if (
    (txtKode.getText().isEmpty()) && (txtJudul.getText().isEmpty()) &&
    (txtAsal.getText().isEmpty()) && (txtTahun.getText().isEmpty()) &&
    (txtStok.getText().isEmpty()) &&
    (String.valueOf(cmbGenre.getSelectedItem())==".: Pilih Judul :.")
    )
 {
    JOptionPane.showMessageDialog(null,"Silahkan Pilih Data dulu untuk proses Ubah");
    JTableFilm.requestFocus();
  } else
 {
        String SQL="UPDATE film SET judul='"+txtJudul.getText()+"', genre='"+String.valueOf(cmbGenre.getSelectedItem())
        +"', tahun='"+txtTahun.getText()+"', asal='"+txtAsal.getText()+"', stok='"+txtStok.getText()
        +"' WHERE KodeFilm='"+txtKode.getText()+"'";
        new ConfigDB().ubahData(SQL);
        new ConfigDB().tampilTabel(judulKolom, sqlFilm, JTableFilm);
        new ConfigDB().aturLebarKolom(JTableFilm, lebarKolom);
        }
 } catch (Exception e)
    {
 System.out.print(e.toString());
 }

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        try {
    if (
        (txtKode.getText().isEmpty()) && (txtJudul.getText().isEmpty()) &&
        (txtAsal.getText().isEmpty()) && (txtTahun.getText().isEmpty()) &&
        (txtStok.getText().isEmpty()) &&
        (String.valueOf(cmbGenre.getSelectedItem())==".: Pilih Judul :.")
       )
    {
        JOptionPane.showMessageDialog(null,"Silahkan Pilih Data dulu untuk proses Hapus");
        JTableFilm.requestFocus();
    } else
 {
        String SQL="DELETE FROM film WHERE KodeFilm='"+txtKode.getText()+"'";
        new ConfigDB().hapusData(SQL);
        new ConfigDB().tampilTabel(judulKolom, sqlFilm, JTableFilm);
        new ConfigDB().aturLebarKolom(JTableFilm, lebarKolom);
    }
    } catch (Exception e)
 {
 System.out.print(e.toString());
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:      
    txtKode.setText(null);
    txtJudul.setText(null);
    txtAsal.setText(null);
    txtStok.setText(null);
    txtTahun.setText(null);
    cmbGenre.setSelectedItem(String.valueOf(".: Pilih Judul :."));  
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:   
        new ConfigDB().tampilTabel(judulKolom, sqlFilm, JTableFilm);
        new ConfigDB().aturLebarKolom(JTableFilm, lebarKolom);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void JTableFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableFilmMouseClicked
        // TODO add your handling code here:    
        try {
    int baris = JTableFilm.getSelectedRow();
        txtKode.setText(String.valueOf(JTableFilm.getValueAt(baris,0)));
        txtJudul.setText(String.valueOf(JTableFilm.getValueAt(baris,1)));
        cmbGenre.setSelectedItem(String.valueOf(JTableFilm.getValueAt(baris,2)));
        txtTahun.setText(String.valueOf(JTableFilm.getValueAt(baris,3)));
        txtAsal.setText(String.valueOf(JTableFilm.getValueAt(baris,4)));
        txtStok.setText(String.valueOf(JTableFilm.getValueAt(baris,5)));
 } catch (Exception e) {
  System.out.print(e.toString());
 }     
    }//GEN-LAST:event_JTableFilmMouseClicked

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:   
    try {
        String SQL="SELECT*FROM film WHERE judul like '%"+txtCari.getText()+"%'";
        new ConfigDB().cariData(judulKolom, SQL, JTableFilm);
    } catch (Exception e) {
    System.out.print(e.toString());
        }
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formFilem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formFilem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formFilem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formFilem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formFilem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel JLabel6;
    private javax.swing.JLabel JLabel7;
    private javax.swing.JTable JTableFilm;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbGenre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
